### ISSUE TITLE
[FEATURE REQUEST] Consider merging with `@faker-js/faker`

### ISSUE THREAD

**Issue by damienwebdev** [luciferreeves/blaver#17]
Hey, I saw this repo and was wondering if you'd want to be a maintainer in the[ `@faker-js`](https://github.com/faker-js/faker) org. If not, more power to you! But, we've got a little community going and it may be easier than solo maintenance.

**Comment by luciferreeves** [comment]
Hi,

I appreciate the idea. However, one of the main ideas of this project depends on keeping a short and unique name in NPM rather than `@someuser/some-library`. Also, I am working with a few friends and we are in the midst of deploying new features - I am considering a few ideas. Please give me some time to work upon these things and if I feel like merging this with `@faker-js/faker`, I would send a request to do so.

I have seen your project and I have starred your repository so that I can visit there time to time. I am also thinking of writing a few fixes for `@faker-js/faker` myself in my free time. I believe you have a nice community going and I would love to be a part of it - I would be contributing soon enough in `@faker-js/faker`.

Thank you for the offer again. Feel free to carry this conversation forward if you like. I would love to hear more. Leaving this issue open.

**Comment by luciferreeves** [comment]
No further updates received. Closing issue.
